apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjU2LjI1MDo4MDgzIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NmNtVmthR0YwIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
