apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.image.containerport }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
  selector:
    app: myproject-test
  type: NodePort
