apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myproject
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myproject-test
  template:
    metadata:
      labels:
        app: myproject-test
    spec:
      containers:
      - name: myproject-cd
        image: 192.168.56.250:8083/myproject:1.52
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP      
      imagePullSecrets:
        - name: nexusrepo-dev     
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 30
      - setWeight: 20
