apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myproject
  namespace: duclo-dev
spec:
  selector:
    matchLabels:
      app: myproject-test
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: myproject-test
    spec:
      containers:
      - name: myproject-dev
        image: 192.168.56.250:8083/myproject:1.58
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: nexusrepo-dev
    strategy:
      canary: #Indicates that the rollout should use the Canary strategy
        maxSurge: "25%"
        maxUnavailable: 0
        steps:
        - setWeight: 10
        - pause:
            duration: 3m # 1 hour
        - setWeight: 20
        - pause: {} # pause indefinitely
