apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysaccount-deployment
  namespace: sysadmin-account
spec:
  selector:
    matchLabels:
      app: sysadmin-account-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: sysadmin-account-app
    spec:
      containers:
      - name: sysadmin-account-dev
        image: 192.168.56.250:8085/backend-sysadmin-account:v0.0.1-7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
          - configMapRef:
              name: account-configmap
    
      imagePullSecrets:
        - name: nxu-sa-repo
