apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
secrets:
- name: default-token-6srfx
imagePullSecrets:
- name: {{ .Values.secret.name }}
