# Default values for duclo-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: duclo-dev
name: myproject-dev

replicaCount: 10

image:
  repository: 192.168.56.250:8083/myproject
  pullPolicy: IfNotPresent
  tag: "1.BID"
  containerport: 8080

imagePullSecrets: nexusrepo-dev

service:
  name: duclo-dev-service
  nodePort: 30033

